// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvt560sHO7JrslFi1KCqwYryMxIpXoII4',
    appId: '1:842721306681:web:ec89a14bb38c3196ac45e8',
    messagingSenderId: '842721306681',
    projectId: 'taskly-f2a76',
    authDomain: 'taskly-f2a76.firebaseapp.com',
    storageBucket: 'taskly-f2a76.firebasestorage.app',
    measurementId: 'G-T1P1F6PJZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEk5Q4kwG81Bc7G6CZG1kkGgNvAGDR1-A',
    appId: '1:842721306681:android:df730c18408a4a8eac45e8',
    messagingSenderId: '842721306681',
    projectId: 'taskly-f2a76',
    storageBucket: 'taskly-f2a76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrljiNtumou1kUtfVk0IEvUsp3B1SiDmk',
    appId: '1:842721306681:ios:3930c28f4c7e4145ac45e8',
    messagingSenderId: '842721306681',
    projectId: 'taskly-f2a76',
    storageBucket: 'taskly-f2a76.firebasestorage.app',
    iosBundleId: 'com.example.boradingWeek2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrljiNtumou1kUtfVk0IEvUsp3B1SiDmk',
    appId: '1:842721306681:ios:3930c28f4c7e4145ac45e8',
    messagingSenderId: '842721306681',
    projectId: 'taskly-f2a76',
    storageBucket: 'taskly-f2a76.firebasestorage.app',
    iosBundleId: 'com.example.boradingWeek2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvt560sHO7JrslFi1KCqwYryMxIpXoII4',
    appId: '1:842721306681:web:1e6dd9dbacaea87cac45e8',
    messagingSenderId: '842721306681',
    projectId: 'taskly-f2a76',
    authDomain: 'taskly-f2a76.firebaseapp.com',
    storageBucket: 'taskly-f2a76.firebasestorage.app',
    measurementId: 'G-L5XCV1FD5W',
  );

}